spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ManagementStudents
#    url: jdbc:postgresql://localhost:5432/test
    password: Thienphu1
    username: postgres
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
    generate-ddl: true
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  mail:
    host: smtp.gmail.com
    password: nhutaikhoan
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
    username: phailamsaonana@gmail.com
    default-encoding: UTF-8
  #
  jackson:
    default-property-inclusion: non_null
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

#logging:
#  level:
#    org:
#      hibernate: DEBUG




